importScripts("precache-manifest.57f00a9391b94c5c53f467943a69acf2.js", "https://storage.googleapis.com/workbox-cdn/releases/4.2.0/workbox-sw.js");

// manifest import and workbox imports will be autogenerated by webpack
workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
