importScripts("precache-manifest.5a07364fbc0b412fd710cea4a122ba21.js", "https://storage.googleapis.com/workbox-cdn/releases/4.2.0/workbox-sw.js");

// manifest import and workbox imports will be autogenerated by webpack
workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
